# Generated by Django 4.1 on 2022-09-01 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NewsItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, unique=True, verbose_name='Название новости')),
                ('description', models.TextField(verbose_name='Описание поста')),
                ('image', models.ImageField(blank=True, default=None, null=True, upload_to='', verbose_name='Картинка новости')),
                ('creation_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания поста')),
            ],
            options={
                'verbose_name': 'Новость',
                'verbose_name_plural': 'Новости',
            },
        ),
    ]
